# File URL:
# https://cdn.jsdelivr.net/gh/tohodo/autofill@main/filename.md
name: Purge CDN cache

on:
  # Trigger the workflow on push for the "main" branch
  push:
    branches: ["main"]
  # Allow this workflow to be ran manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "purge"
  purge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Run a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          curl -X POST \
            https://purge.jsdelivr.net/ \
            -H 'content-type: application/json' \
            -d '{
                  "path": [
                    "/gh/tohodo/autofill@main/news-2022.md",
                    "/gh/tohodo/autofill@main/news-2023.md",
                    "/gh/tohodo/autofill@main/news-2024.md",
                    "/gh/tohodo/autofill@main/news-update.md",
                    "/gh/tohodo/autofill@main/support-links.md"
                  ]
                }'
